version: '2'

services:
    db:
        image: public-docker-virtual.artnj.zte.com.cn/postgres
        environment:
            POSTGRES_PASSWORD: qwe123
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data/

    nginx:
        build: ./nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./nginx_data/:/app/nginx_data
            - ./log:/var/log/nginx
        depends_on:
            - web

    web:
        build: .
        command: uwsgi --ini uwsgi.ini
        restart: always
        volumes:
            - ./web_data:/app/web_data
        ports:
            - "8001:8001"
        depends_on:
            - db

volumes:
    mysite_data:
    pgdata: